/* Flowboard's dependency-free state and data helpers. Browser global + Node test module. */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.FlowboardState = api;
})(typeof globalThis === 'undefined' ? this : globalThis, function () {
  'use strict';
  const SCHEMA_VERSION = 4;
  const COLORS = ['green', 'purple', 'orange', 'red'];
  const roles = ['owner', 'editor', 'viewer'];
  const accessModes = ['private', 'shared', 'read-only'];
  const seedLists = [{title:'Ideas',cards:[['purple','Research competitor landing pages','💬 3'],['orange','Collect customer testimonials','📎 2'],['','Plan launch announcement','']]},{title:'To do',cards:[['red','Write homepage copy','📅 Jul 31'],['orange','Create social media graphics','📎 4'],['','Set up analytics events','']]},{title:'In progress',cards:[['purple','Design responsive homepage','💬 5'],['','Build email signup form','📅 Aug 2']]},{title:'Done',cards:[['','Choose brand colour palette','✓ Complete'],['','Set project goals','✓ Complete']]}];
  const uid = () => globalThis.crypto?.randomUUID?.() || `fb-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const now = () => new Date().toISOString();
  const cleanColor = color => COLORS.includes(color) ? color : 'green';
  const cleanRole = role => roles.includes(role) ? role : 'viewer';
  const cleanAccess = access => accessModes.includes(access) ? access : 'private';
  const activity = text => ({id:uid(), text, at:now()});
  const makeCard = (title, color = '', meta = '') => ({id:uid(), title:String(title || 'Untitled card'), description:'', labels:color ? [{id:uid(), color:cleanColor(color), name:''}] : [], dueDate:'', dueTime:'', checklist:[], assignees:[], meta:String(meta || ''), activity:[activity('Card created')], createdAt:now(), updatedAt:now(), archived:false, archivedAt:''});
  const makeList = (title, cards = []) => ({id:uid(), title:String(title || 'Untitled list'), cards, createdAt:now(), updatedAt:now(), archived:false});
  function makeCollaboration() { const member = {id:uid(), name:'Local owner', role:'owner', addedAt:now()}; return {access:'private', currentMemberId:member.id, members:[member], updatedAt:now()}; }
  function normalizeCollaboration(data) { const members = Array.isArray(data?.members) ? data.members.map(member => ({id:member?.id || uid(), name:String(member?.name || 'Unnamed member').trim().slice(0,80) || 'Unnamed member', role:cleanRole(member?.role), addedAt:member?.addedAt || now()})).slice(0,50) : []; if (!members.length) return makeCollaboration(); if (!members.some(member => member.role === 'owner')) members[0].role = 'owner'; return {access:cleanAccess(data?.access), currentMemberId:members.some(member => member.id === data?.currentMemberId) ? data.currentMemberId : members[0].id, members, updatedAt:data?.updatedAt || now()}; }
  function makeBoard(template = 'launch') { const collaboration = makeCollaboration(), base = {id:uid(), createdAt:now(), updatedAt:now(), archived:false, collaboration}; if (template === 'blank') return {...base, title:'Untitled board', lists:[]}; if (template === 'tasks') return {...base, title:'Personal tasks', lists:['To do','Doing','Done'].map(title => makeList(title))}; return {...base, title:'Website Launch', lists:seedLists.map(list => makeList(list.title, list.cards.map(card => makeCard(card[1], card[0], card[2]))))}; }
  const makeWorkspace = () => { const initial = makeBoard(); return {schemaVersion:SCHEMA_VERSION, activeBoardId:initial.id, boards:[initial], preferences:{theme:'system'}}; };
  function normalizeLabel(label) { return typeof label === 'string' ? {id:uid(), color:cleanColor(label), name:''} : {id:label?.id || uid(), color:cleanColor(label?.color), name:String(label?.name || '')}; }
  function normalizeCard(card) { return {id:card?.id || uid(), title:String(card?.title || 'Untitled card'), description:String(card?.description || ''), labels:Array.isArray(card?.labels) ? card.labels.map(normalizeLabel) : [], dueDate:/^\d{4}-\d{2}-\d{2}$/.test(card?.dueDate || '') ? card.dueDate : '', dueTime:/^\d{2}:\d{2}$/.test(card?.dueTime || '') ? card.dueTime : '', checklist:Array.isArray(card?.checklist) ? card.checklist.map(item => ({id:item?.id || uid(), text:String(item?.text || ''), done:Boolean(item?.done)})) : [], assignees:Array.isArray(card?.assignees) ? card.assignees.map(String).filter(Boolean).slice(0,8) : [], meta:String(card?.meta || ''), activity:Array.isArray(card?.activity) ? card.activity.map(item => ({id:item?.id || uid(), text:String(item?.text || ''), at:item?.at || now()})).slice(-25) : [activity('Card created')], createdAt:card?.createdAt || now(), updatedAt:card?.updatedAt || now(), archived:Boolean(card?.archived), archivedAt:card?.archivedAt || ''}; }
  function normalizeBoard(board) { return {id:board?.id || uid(), title:String(board?.title || 'Untitled board'), lists:Array.isArray(board?.lists) ? board.lists.map(list => ({id:list?.id || uid(), title:String(list?.title || 'Untitled list'), cards:Array.isArray(list?.cards) ? list.cards.map(normalizeCard) : [], createdAt:list?.createdAt || now(), updatedAt:list?.updatedAt || now(), archived:Boolean(list?.archived)})) : [], createdAt:board?.createdAt || now(), updatedAt:board?.updatedAt || now(), archived:Boolean(board?.archived), collaboration:normalizeCollaboration(board?.collaboration)}; }
  function normalizeWorkspace(data) { const boards = Array.isArray(data?.boards) ? data.boards.map(normalizeBoard) : []; const usable = boards.length ? boards : [makeBoard()]; return {schemaVersion:SCHEMA_VERSION, activeBoardId:usable.some(item => item.id === data?.activeBoardId) ? data.activeBoardId : usable[0].id, boards:usable, preferences:{theme:['light','dark','system'].includes(data?.preferences?.theme) ? data.preferences.theme : 'system'}}; }
  const validWorkspace = data => data && [1,2,3,4].includes(data.schemaVersion) && Array.isArray(data.boards);
  const validBoard = data => data && typeof data === 'object' && typeof data.title === 'string' && Array.isArray(data.lists) && !Array.isArray(data.boards);
  function migrateLegacy(data) { if (!Array.isArray(data)) return null; const board = {id:uid(), title:'Website Launch', lists:data.map(list => makeList(list?.title, (list?.cards || []).map(card => makeCard(card?.title, card?.color, card?.meta)))), createdAt:now(), updatedAt:now(), archived:false}; return normalizeWorkspace({schemaVersion:SCHEMA_VERSION, activeBoardId:board.id, boards:[board], preferences:{theme:'system'}}); }
  function dueState(card, today = new Date().toISOString().slice(0,10)) { if (!card.dueDate) return 'none'; const complete = card.checklist?.length && card.checklist.every(item => item.done); return complete ? 'complete' : card.dueDate < today ? 'overdue' : card.dueDate === today ? 'today' : 'upcoming'; }
  function cardMatches(card, search = '', filters = {due:'all', label:'all'}, today) { const text = [card.title, card.description, ...(card.labels || []).map(label => label.name), ...(card.checklist || []).map(item => item.text), ...(card.assignees || [])].join(' ').toLowerCase(); return text.includes(String(search).toLowerCase()) && (filters.due === 'all' || dueState(card, today) === filters.due) && (filters.label === 'all' || (card.labels || []).some(label => label.color === filters.label)); }
  function describeImport(data) { const workspace = validWorkspace(data) ? normalizeWorkspace(data) : null; const importedBoard = validBoard(data?.board) ? normalizeBoard(data.board) : validBoard(data) ? normalizeBoard(data) : null; if (!workspace && !importedBoard) return null; const boards = workspace ? workspace.boards : [importedBoard]; const lists = boards.reduce((sum,item) => sum + item.lists.length, 0), cards = boards.reduce((sum,item) => sum + item.lists.reduce((inner,list) => inner + list.cards.length,0),0); return {workspace, importedBoard, counts:{boards:boards.length, lists, cards}, text:`${workspace ? 'Workspace' : 'Board'} ready: ${boards.length} board${boards.length === 1 ? '' : 's'}, ${lists} list${lists === 1 ? '' : 's'}, ${cards} card${cards === 1 ? '' : 's'}.`}; }
  function csvForBoard(board) { const quote = value => `"${String(value ?? '').replace(/"/g,'""')}"`; const rows = [['Board','List','Card title','Description','Labels','Due date','Due time','Assignees','Archived']]; board.lists.forEach(list => list.cards.forEach(card => rows.push([board.title,list.title,card.title,card.description,(card.labels || []).map(label => label.name || label.color).join('; '),card.dueDate,card.dueTime,(card.assignees || []).join('; '),card.archived ? 'Yes' : 'No']))); return rows.map(row => row.map(quote).join(',')).join('\r\n'); }
  const clone = value => JSON.parse(JSON.stringify(value));
  function pushUndo(history, label, workspace, limit = 20) { return [...history, {label, workspace:clone(workspace)}].slice(-limit); }
  function takeUndo(history) { if (!history.length) return {history, item:null}; return {history:history.slice(0,-1), item:history.at(-1)}; }
  return {SCHEMA_VERSION, COLORS, uid, now, cleanColor, cleanRole, cleanAccess, activity, makeCard, makeList, makeCollaboration, normalizeCollaboration, makeBoard, makeWorkspace, normalizeWorkspace, validWorkspace, validBoard, migrateLegacy, dueState, cardMatches, describeImport, csvForBoard, clone, pushUndo, takeUndo};
});
