const $ = selector => document.querySelector(selector);
const timestamp = value => value?.toDate?.() || (value instanceof Date ? value : null);

export function initializeCommentsUI(adapter) {
  const dialog=$('#card-dialog'), section=$('#cloud-comments-section'), list=$('#cloud-comments-list'), status=$('#cloud-comments-status'), count=$('#cloud-comments-count'), load=$('#load-older-comments'), composer=$('#cloud-comment-form'), input=$('#cloud-comment-input'), add=$('#add-cloud-comment'), readonly=$('#cloud-comments-readonly'), removeDialog=$('#comment-delete-dialog');
  let session=null, active=null, stopListener=null, generation=0, live=[], older=[], cursor=null, hasMore=false, members=new Map(), pendingRemoval=null, busy=false;
  const stop=()=>{generation+=1; stopListener?.(); stopListener=null; active=null; live=[]; older=[]; cursor=null; hasMore=false; members.clear(); list.replaceChildren(); status.textContent=''; count.textContent=''; section.hidden=true;};
  const context=()=>{const mode=globalThis.FlowboardApp?.getMode?.(), boardId=globalThis.FlowboardApp?.getActiveBoardId?.(), cardId=dialog.dataset.cardId;return mode && ['cloud','cloud-preview'].includes(mode.kind) && mode.id && boardId && cardId ? {workspaceId:mode.id,boardId,cardId,role:mode.role,editable:mode.kind==='cloud'} : null;};
  const authorName=uid=>uid===session?.uid?'You':members.get(uid)?.displayName || 'Former member';
  const formatTime=value=>{const date=timestamp(value);return date?date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Pending';};
  const allEntries=()=>{const byId=new Map([...older,...live].map(entry=>[entry.id,entry]));return [...byId.values()].sort((a,b)=>(timestamp(a.createdAt)?.getTime()||0)-(timestamp(b.createdAt)?.getTime()||0));};
  const button=(label,action,id,quiet=true)=>{const control=document.createElement('button');control.type='button';control.className=quiet?'text-button':'button button-primary';control.textContent=label;control.dataset.action=action;control.dataset.commentId=id;return control;};
  const render=()=>{
    const entries=allEntries(); list.replaceChildren(); count.textContent=entries.length?`${entries.length} loaded`:'';
    if(!entries.length){const empty=document.createElement('li');empty.className='empty compact';empty.textContent='No cloud comments yet.';list.append(empty);}
    entries.forEach(entry=>{const item=document.createElement('li');item.className='comment-item';item.dataset.commentId=entry.id;const meta=document.createElement('div');meta.className='comment-meta';const author=document.createElement('strong');author.textContent=authorName(entry.authorUid);const time=document.createElement('time');time.textContent=formatTime(entry.updatedAt || entry.createdAt);const date=timestamp(entry.updatedAt || entry.createdAt);if(date)time.dateTime=date.toISOString();meta.append(author,time);const body=document.createElement('p');body.className=entry.deletedAt?'comment-body comment-deleted':'comment-body';body.textContent=entry.deletedAt?'Comment removed.':entry.body;item.append(meta,body);
      if(!entry.deletedAt && active?.editable && (entry.authorUid===session?.uid || active.role==='owner')){const actions=document.createElement('div');actions.className='comment-actions';if(entry.authorUid===session?.uid)actions.append(button('Edit','edit-comment',entry.id));actions.append(button('Remove','remove-comment',entry.id));item.append(actions);}list.append(item);});
    load.hidden=!hasMore;load.disabled=false;
  };
  const fail=message=>error=>{console.error(message,error);status.textContent=error?.message || message;};
  const open=async()=>{stop();const next=context();if(!next||!session)return;active=next;section.hidden=false;composer.hidden=!next.editable;readonly.hidden=next.editable;input.value='';status.textContent='Loading cloud comments...';const token=generation;
    try{const currentMembers=await adapter.listMembers(next.workspaceId);if(token!==generation)return;members=new Map(currentMembers.map(member=>[member.uid,member]));stopListener=await adapter.subscribeComments({...next,pageSize:25,onComments:page=>{if(token!==generation)return;live=page.entries;cursor=page.cursor;hasMore=page.hasMore;status.textContent='Comments are current.';render();},onError:fail('Cloud comments stopped updating.')});if(token!==generation){stopListener?.();stopListener=null;}}catch(error){if(token===generation)fail('Cloud comments could not be loaded.')(error);}};
  const entryFor=id=>allEntries().find(entry=>entry.id===id);
  const beginEdit=entry=>{const item=list.querySelector(`[data-comment-id="${CSS.escape(entry.id)}"]`), body=item?.querySelector('.comment-body'), actions=item?.querySelector('.comment-actions');if(!item||!body||!actions)return;const edit=document.createElement('textarea');edit.className='comment-edit-input';edit.maxLength=2000;edit.value=entry.body;body.replaceWith(edit);actions.replaceChildren(button('Cancel','cancel-edit',entry.id),button('Save','save-edit',entry.id,false));edit.focus();};
  const mutation=async(action,success)=>{if(!active||busy)return false;busy=true;add.disabled=true;status.textContent='Saving comment...';try{await action();status.textContent=success;return true;}catch(error){fail('The comment change failed.')(error);return false;}finally{busy=false;add.disabled=false;}};
  add.addEventListener('click',()=>{const body=input.value.trim();if(!body)return input.focus();const snapshot={...active};mutation(()=>adapter.createComment({...snapshot,body}), 'Comment added.').then(saved=>{if(saved&&active?.cardId===snapshot.cardId)input.value='';});});
  load.addEventListener('click',async()=>{if(!active||!cursor)return;load.disabled=true;status.textContent='Loading older comments...';try{const page=await adapter.listOlderComments({...active,cursor,pageSize:25});older=[...older,...page.entries];cursor=page.cursor;hasMore=page.hasMore;status.textContent='Older comments loaded.';render();}catch(error){fail('Older comments could not be loaded.')(error);}finally{load.disabled=false;}});
  list.addEventListener('click',event=>{const control=event.target.closest('[data-action]');if(!control)return;const entry=entryFor(control.dataset.commentId);if(!entry)return;if(control.dataset.action==='edit-comment')beginEdit(entry);if(control.dataset.action==='cancel-edit')render();if(control.dataset.action==='save-edit'){const body=control.closest('.comment-item').querySelector('textarea')?.value.trim();if(!body)return;mutation(()=>adapter.updateComment({...active,commentId:entry.id,revision:entry.revision,body}),'Comment updated.');}if(control.dataset.action==='remove-comment'){pendingRemoval=entry;removeDialog.showModal();}});
  removeDialog.addEventListener('close',()=>{const entry=pendingRemoval;pendingRemoval=null;if(removeDialog.returnValue==='confirm'&&entry)mutation(()=>adapter.removeComment({...active,commentId:entry.id,revision:entry.revision}),'Comment removed.');});
  new MutationObserver(()=>dialog.open?open():stop()).observe(dialog,{attributes:true,attributeFilter:['open']});
  window.addEventListener('flowboard:cloud-preview-change',stop);
  return {setSession(next){session=next;if(!session)stop();else if(dialog.open)open();}};
}
